### ISSUE TITLE
Feature Request — Limit child plugins.

### ISSUE THREAD

**Issue by mishbahr** [digital-anvil/djangocms-owl#1]
Add settings option to limit child plugins. 
 
settings.py

    DJANGOCMS_OWL_CHILD_CLASSES = ['FilerImagePlugin', ]

cms_plugins.py

    child_classes = settings.DJANGOCMS_OWL_CHILD_CLASSES

**Comment by leesolway** [comment]
Good suggestion.
The change has been pushed.
