### ISSUE TITLE
Auto sync issue

### ISSUE THREAD

**Issue by MUDASSARHASHMI** [digital-anvil/djangocms-owl#3]
After installation and adding it to settings following error occured.

```
ERRORS:
djangocms_owl.OwlCarousel.cmsplugin_ptr: (fields.E300) Field defines a relation
with model 'CMSPlugin', which is either not installed, or is abstract.
```

**Comment by leesolway** [comment]
Is this using the version from PIP? 

Any chance you could give me Django / CMS version numbers please and i shall take a look.
